module CountryFlags

let countryToFlag =
  Map [
    "Sverige", "🇸🇪"
    "England", "🇬🇧"
    "Frankrike", "🇫🇷"
    "Tyskland", "🇩🇪"
    "Spanien", "🇪🇸"
    "Italien", "🇮🇹"
    "Nederländerna", "🇳🇱"
    "Portugal", "🇵🇹"
    "Schweiz", "🇨🇭"
    "Turkiet", "🇹🇷"
    "Kroatien", "🇭🇷"
    "Belgien", "🇧🇪"
    "Danmark", "🇩🇰"
    "Polen", "🇵🇱"
    "Tjeckien", "🇨🇿"
    "Serbien", "🇷🇸"
    "Skottland", "🏴󠁧󠁢󠁳󠁣󠁴󠁿"
    "Norge", "🇳🇴"
    "Finland", "🇫🇮"
    "Island", "🇮🇸"
    "Ukraina", "🇺🇦"
    "Ryssland", "🇷🇺"
    "Österrike", "🇦🇹"
    "Ungern", "🇭🇺"
    "Rumänien", "🇷🇴"
    "Slovakien", "🇸🇰"
    "Slovenien", "🇸🇮"
    "Grekland", "🇬🇷"
    "Irland", "🇮🇪"
    "Wales", "🏴󠁧󠁢󠁷󠁬󠁳󠁿"
    "Albanien", "🇦🇱"
    "Bulgarien", "🇧🇬"
    "Bosnien", "🇧🇦"
    "Nordmakedonien", "🇲🇰"
    "Luxemburg", "🇱🇺"
    "Georgien", "🇬🇪"
    "Kosovo", "🇽🇰"
    "Estland", "🇪🇪"
    "Lettland", "🇱🇻"
    "Litauen", "🇱🇹"
    "Montenegro", "🇲🇪"
    "Armenien", "🇦🇲"
    "Azerbajdzjan", "🇦🇿"
    "Israel", "🇮🇱"
    "Malta", "🇲🇹"
    "Cypern", "🇨🇾"
    "Kazakstan", "🇰🇿"
    "Liechtenstein", "🇱🇮"
    "Andorra", "🇦🇩"
    "San Marino", "🇸🇲"
    "Färöarna", "🇫🇴"
    "Gibraltar", "🇬🇮"
    "Moldavien", "🇲🇩"
    "Vitryssland", "🇧🇾"
    "USA", "🇺🇸"
    "Brasilien", "🇧🇷"
    "Argentina", "🇦🇷"
    "Mexiko", "🇲🇽"
    "Japan", "🇯🇵"
    "Sydkorea", "🇰🇷"
    "Australien", "🇦🇺"
    "Kanada", "🇨🇦"
    "Kina", "🇨🇳"
    // Lägg till fler vid behov
  ]
